name: Node.js Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependecies
        run: npm install

      - name: Build the ZIP Artifact
        run: |
          zip -r my-node-api.zip ./

      - name: Upload Artifact to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: my-node-api-zip
          path: my-node-api.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: my-node-api-zip
          path: ./build-artifact

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name my-node-api-function \
            --zip-file fileb://./build-artifact/my-node-api.zip
