name: Deploy to AWS Lambda

on:
  workflow_run:
    workflows: ["Node.js Build and Release"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-acess-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: my-node-api-zip
          path: ./build-artifact

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name my-node-api-function \
            --zip-file fileb://./build-artifact/my-node-api.zip
